---
name: Setup
description: Setup Node.js and propagate the environment.

runs:
  using: composite
  steps:
    - name: Propagate environment
      shell: bash
      run: |
        echo "ACTIONS_RUNTIME_TOKEN=$ACTIONS_RUNTIME_TOKEN" >> "$GITHUB_ENV" \
        echo "ACTIONS_RUNTIME_URL=$ACTIONS_RUNTIME_URL" >> "$GITHUB_ENV"
