---
name: Setup
description: Setup Node.js and propagate the environment.

runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: npm ci
    - name: Test
      shell: bash
      run: node ./
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
        ACTIONS_RUNTIME_URL: ${{ env.ACTIONS_RUNTIME_URL }}
