---
name: Check

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Get Actions Env
        uses: ./.github/actions/env
      - name: Run Tests
        run: node ./